// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCE2-UY-URYf4wPCOm__Gr8XlU3YNF7Iuc',
    appId: '1:854174072039:web:2b91f44c1d203d902bb642',
    messagingSenderId: '854174072039',
    projectId: 'appblocker-d4e6b',
    authDomain: 'appblocker-d4e6b.firebaseapp.com',
    storageBucket: 'appblocker-d4e6b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3e3TL2eg2-ZuTdyQxID6BE2EV-yNkTCc',
    appId: '1:854174072039:android:2f8fab2bb2e298632bb642',
    messagingSenderId: '854174072039',
    projectId: 'appblocker-d4e6b',
    storageBucket: 'appblocker-d4e6b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMknod57yuoU9OERQCsgWZqqbLmWU7NDE',
    appId: '1:854174072039:ios:6411cdbc3475ac952bb642',
    messagingSenderId: '854174072039',
    projectId: 'appblocker-d4e6b',
    storageBucket: 'appblocker-d4e6b.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMknod57yuoU9OERQCsgWZqqbLmWU7NDE',
    appId: '1:854174072039:ios:6411cdbc3475ac952bb642',
    messagingSenderId: '854174072039',
    projectId: 'appblocker-d4e6b',
    storageBucket: 'appblocker-d4e6b.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCE2-UY-URYf4wPCOm__Gr8XlU3YNF7Iuc',
    appId: '1:854174072039:web:24db84cdf2d63af82bb642',
    messagingSenderId: '854174072039',
    projectId: 'appblocker-d4e6b',
    authDomain: 'appblocker-d4e6b.firebaseapp.com',
    storageBucket: 'appblocker-d4e6b.firebasestorage.app',
  );
}
